minimum_pre_commit_version: "4.0.0"
default_install_hook_types:
  - pre-push
default_stages:
  - pre-push
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: node scripts/run_python_in_venv.js -m ruff check .
        language: system
        pass_filenames: false
        verbose: true
      - id: black-check
        name: black --check
        entry: node scripts/run_python_in_venv.js -m black --check .
        language: system
        pass_filenames: false
        verbose: true
      - id: isort-check
        name: isort --check-only
        entry: node scripts/run_python_in_venv.js -m isort --check-only .
        language: system
        pass_filenames: false
        verbose: true
